title: "Waruim Oojin"
description: "A DevOps Engineer passionate about automation, cloud infrastructure, and CI/CD."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://waruimoojin.github.io" # use your GitHub Pages URL

theme: minima
# If you want to use minima with custom navigation, ensure _data/navigation.yml exists

author:
  name: "Waruim Oojin"
  avatar: "/assets/images/eren.png" # optional, if you upload your avatar image
  bio: "DevOps Engineer passionate about automation, cloud infrastructure, and CI/CD."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/waruimoojin"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/waruimoojin"

show_excerpts: true # Show post excerpts on the homepage
paginate: 5         # Posts shown per page

# Social links in site/footer (minima offers a few)
github_username: "waruimoojin"
gitlab_username: "waruimoojin"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Plugins (minima supports plugins, cayman doesn't)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation settings (optional, minima shows recent posts and pages by default)
# If you want to use custom nav data from _data/navigation.yml,
# make sure your theme supports it

# Collections
collections:
  posts:
    output: true
  about:
    output: true

# Exclude these files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Minima theme colors (Optional, for customization)
minima:
  skin: auto
