# _config.yml

# Tells GitHub Pages to use the minimal-mistakes-jekyll theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # Or "dark", "contrast", "dirt", etc.

# --- Basic Site Settings ---
title: "Waruim Oojin's DevOps Portfolio"
name: "Waruim Oojin"
description: "A DevOps Engineer passionate about automation, cloud infrastructure, and CI/CD."
