name: "Waruim Oojin"
description: "A DevOps Engineer passionate about automation, cloud infrastructure, and CI/CD."

# --- Author Settings ---
# This is used for the sidebar and other places
author:
  name: "Waruim Oojin"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/waruimoojin"
# --- Header ---
# Show the navigation links in the masthead
masthead_nav: true

# --- Navigation ---
navigation:   _data/navigation.yml  