name: "Waruim Oojin"
description: "A DevOps Engineer passionate about automation, cloud infrastructure, and CI/CD."
theme: jekyll-theme-cayman

author:
  name: "Waruim Oojin"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/waruimoojin"

masthead_nav: true
# Remove navigation: _data/navigation.yml
